CREATE TABLE "statement" (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    statement VARCHAR(255) NOT NULL UNIQUE,
    rank INT NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
